<?php
// AUTO-GENERATED by deploy_flutter.ps1
if (!isset($_GET['s']) || $_GET['s'] !== '%%SECRET%%') {
    http_response_code(403); die('403 Forbidden');
}
set_time_limit(300);
ini_set('display_errors', 1);
error_reporting(E_ALL);

$home = '/home/it67y1462n52';
$doc  = '/home/it67y1462n52/public_html/app.caresoko.com';

header('Content-Type: text/html; charset=utf-8');
header('X-Accel-Buffering: no');
echo '<!DOCTYPE html><html><body style="background:#111;color:#ddd;font-family:monospace;padding:20px">';
echo '<h2 style="color:#7af">Caresoko Flutter Web &mdash; Live Deployment</h2>';
ob_flush(); flush();

function run($label, $cmd) {
    echo "<h3 style='color:#fa0;margin-top:16px'>&rsaquo; {$label}</h3>";
    echo "<pre style='background:#222;padding:8px;border-radius:4px;white-space:pre-wrap'>";
    ob_flush(); flush();
    $out = []; $code = 0;
    exec($cmd . ' 2>&1', $out, $code);
    foreach ($out as $l) { echo htmlspecialchars($l) . "\n"; }
    $col = $code === 0 ? '#4f4' : '#f44';
    echo "</pre><p style='color:{$col}'>Exit: {$code}</p>";
    ob_flush(); flush();
    return $code;
}

// Extract each chunk into the doc root
$chunks = glob("{$home}/caresoko_flutter_*.zip");
sort($chunks);
$total = count($chunks);
if ($total === 0) {
    echo "<h3 style='color:#f44'>No flutter chunks found in {$home}</h3>";
    ob_flush(); flush();
} else {
    foreach ($chunks as $i => $chunk) {
        $num = $i + 1;
        run("Chunk {$num}/{$total} - " . basename($chunk),
            "unzip -o \"{$chunk}\" -d {$doc}/ && rm -f \"{$chunk}\"");
    }
}

// Fix file permissions
run('Fix permissions', "find {$doc} -type f -exec chmod 644 {} \\; ; find {$doc} -type d -exec chmod 755 {} \\;");

echo '<h2 style="color:#4f4;border-top:1px solid #444;padding-top:16px">FLUTTER WEB DEPLOYMENT COMPLETE</h2>';
echo '<p>App: <a href="https://app.caresoko.com" style="color:#7af">https://app.caresoko.com</a></p>';
echo '</body></html>';
@unlink(__FILE__);
