import 'package:get/get.dart';
import 'package:gotocarefinder/controller/addproperties_controller.dart';
import 'package:gotocarefinder/controller/add_homecare_controller.dart';
import 'package:gotocarefinder/controller/booking_controller.dart';
import 'package:gotocarefinder/controller/bookingdetails_controller.dart';
import 'package:gotocarefinder/controller/bookrealestate_controller.dart';
import 'package:gotocarefinder/controller/coupon_controller.dart';
import 'package:gotocarefinder/controller/dashboard_controller.dart';
import 'package:gotocarefinder/controller/enquiry_controller.dart';
import 'package:gotocarefinder/controller/extraimage_controller.dart';
import 'package:gotocarefinder/controller/faq_controller.dart';
import 'package:gotocarefinder/controller/gallery_controller.dart';
import 'package:gotocarefinder/controller/gallerycategory_controller.dart';
import 'package:gotocarefinder/controller/galleryimage_controller.dart';
import 'package:gotocarefinder/controller/homepage_controller.dart';
import 'package:gotocarefinder/controller/listofproperti_controller.dart';
import 'package:gotocarefinder/controller/login_controller.dart';
import 'package:gotocarefinder/controller/mybooking_controller.dart';
import 'package:gotocarefinder/controller/myearning_controller.dart';
import 'package:gotocarefinder/controller/notification_controller.dart';
import 'package:gotocarefinder/controller/pagelist_controller.dart';
import 'package:gotocarefinder/controller/payout_controller.dart';
import 'package:gotocarefinder/controller/reviewsummary_controller.dart';
import 'package:gotocarefinder/controller/search_controller.dart';
import 'package:gotocarefinder/controller/selectcountry_controller.dart';
import 'package:gotocarefinder/controller/signup_controller.dart';
import 'package:gotocarefinder/controller/subscribe_controller.dart';
import 'package:gotocarefinder/controller/wallet_controller.dart';
import 'package:shared_preferences/shared_preferences.dart';

init() async {
  final sharedPreferences = await SharedPreferences.getInstance();
  Get.lazyPut(() => sharedPreferences);
  Get.lazyPut(() => HomePageController());
  Get.lazyPut(() => LoginController());
  Get.lazyPut(() => SignUpController());
  Get.lazyPut(() => AddPropertiesController());
  Get.lazyPut(() => AddHomecareController());
  Get.lazyPut(() => BookingDetailsController());
  Get.lazyPut(() => BookrealEstateController());
  Get.lazyPut(() => CouponController());
  Get.lazyPut(() => FaqController());
  Get.lazyPut(() => MyBookingController());
  Get.lazyPut(() => NotificationController());
  Get.lazyPut(() => PageListController());
  Get.lazyPut(() => ReviewSummaryController());
  Get.lazyPut(() => SearchPropertyController());
  Get.lazyPut(() => WalletController());
  Get.lazyPut(() => GalleryController());
  Get.lazyPut(() => SelectCountryController());
  Get.lazyPut(() => SubscribeController());
  Get.lazyPut(() => ListOfPropertiController());
  Get.lazyPut(() => ExtraImageController());
  Get.lazyPut(() => DashBoardController());
  Get.lazyPut(() => GalleryCategoryController());
  Get.lazyPut(() => GalleryImageController());
  Get.lazyPut(() => BookingController());
  Get.lazyPut(() => EnquiryController());
  Get.lazyPut(() => MyEarningController());
  Get.lazyPut(() => PayOutController());
}
